// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs0ixcBVuI0KTRhqBbvkQTvOyE2OPdvB0',
    appId: '1:369132957308:web:eafcbb92e3e74f8dd263f9',
    messagingSenderId: '369132957308',
    projectId: 'schoolapp-b5dfb',
    authDomain: 'schoolapp-b5dfb.firebaseapp.com',
    storageBucket: 'schoolapp-b5dfb.firebasestorage.app',
    measurementId: 'G-23QMFPHLKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSdk16WH-zipPGVgs6ZW_aZgcqrB4vc0Q',
    appId: '1:369132957308:android:c44b1956467e80e0d263f9',
    messagingSenderId: '369132957308',
    projectId: 'schoolapp-b5dfb',
    storageBucket: 'schoolapp-b5dfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA21HFbrormWXOCCepMlaA1UZXoviRROOk',
    appId: '1:369132957308:ios:639462536184ab9cd263f9',
    messagingSenderId: '369132957308',
    projectId: 'schoolapp-b5dfb',
    storageBucket: 'schoolapp-b5dfb.firebasestorage.app',
    iosClientId: '369132957308-rn6rkr0t51aqclvm5rs284205v76v08f.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA21HFbrormWXOCCepMlaA1UZXoviRROOk',
    appId: '1:369132957308:ios:639462536184ab9cd263f9',
    messagingSenderId: '369132957308',
    projectId: 'schoolapp-b5dfb',
    storageBucket: 'schoolapp-b5dfb.firebasestorage.app',
    iosClientId: '369132957308-rn6rkr0t51aqclvm5rs284205v76v08f.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs0ixcBVuI0KTRhqBbvkQTvOyE2OPdvB0',
    appId: '1:369132957308:web:9d00e0a59147d7b5d263f9',
    messagingSenderId: '369132957308',
    projectId: 'schoolapp-b5dfb',
    authDomain: 'schoolapp-b5dfb.firebaseapp.com',
    storageBucket: 'schoolapp-b5dfb.firebasestorage.app',
    measurementId: 'G-JBGXNHTV9V',
  );

}